baseURL = "https://aptsenozx.github.io/"
languageCode = "zh-Hans"
title = "ğŸ¡My Blog"
theme = "hugo-theme-dream"

copyright = '<a rel="license" href="http://creativecommons.org/licenses/by-nc-sa/4.0/"><img alt="çŸ¥è¯†å…±äº«è®¸å¯åè®®" style="border-width:0" src="https://i.creativecommons.org/l/by-nc-sa/4.0/88x31.png" /></a><br />æœ¬ä½œå“é‡‡ç”¨<a rel="license" href="http://creativecommons.org/licenses/by-nc-sa/4.0/">çŸ¥è¯†å…±äº«ç½²å-éå•†ä¸šæ€§ä½¿ç”¨-ç›¸åŒæ–¹å¼å…±äº« 4.0 å›½é™…è®¸å¯åè®®</a>è¿›è¡Œè®¸å¯ã€‚<br /><br />èƒŒæ™¯ä½¿ç”¨äº† <a href="https://www.pexels.com/zh-cn/" target="_blank">Pexels</a> ä¸Š <a href="https://www.pexels.com/zh-cn/@minan1398" target="_blank">Min An</a> æ‹æ‘„çš„<a href="https://www.pexels.com/zh-cn/photo/1454794/" target="_blank">å›¾ç‰‡</a>ã€‚'

enableRobotsTXT = true
enableEmoji = true    
hasCJKLanguage = true
# [services]
# [services.googleAnalytics]
# ID = '...'

#[outputs]
#  home = ["HTML", "RSS", "JSON"]

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
  [markup.tableOfContents]
    startLevel = 2
    endLevel   = 4
    ordered    = false


[params]
  background = "#fff"
  backgroundImage = "./img/background3.jpg"
  linkColor = "seagreen"
  
  lightTheme = "emerald"
  darkTheme = "forest"

  mainSections = ["post", "posts"]

  # dark mode
  defaultDark = true
  backgroundDark = "#333"
  backgroundImageDark = "./img/background3.jpg"
  darkLinkColor = "darkseagreen"
  # darkNav = true
  # dark404 = true

  images = ["./img/background.jpg"]

  author = "å­æ¡”"
  description = "æ—¥å¸¸å­¦ä¹ ç”Ÿæ´»è®°å½•"
  avatar = "./img/å°å”¯.jpg"
  headerTitle = "å­æ¡”çš„åšå®¢"
  motto = "ä½†è¡Œå¥½äº‹ï¼Œè«é—®å‰ç¨‹"
  
  rss = true
  utterancesRepo = "Aptsenozx/Aptsenozx.github.io"
  busuanzi = true
  
  email = "zixuan.wang1206@gmail.com"
  twitter = "o_sisen"
  # facebook = ""
  # instagram = ""
  # linkedin = ""
  github = "Aptsenozx"
  # stackoverflow = ""
  siteStartYear = 2021
  
  favicon = "icon.ico"
  svg = true
  faviconVersion = ""

  highlightjs = true
  # highlightjsCDN = "https://cdn.jsdelivr.net/gh/highlightjs/cdn-release/build/highlight.min.js"
  highlightjsExtraLanguages = ["clojure", "ocaml"]
  highlightjsTheme = "gruvbox-light"
  highlightjsThemeDark = "gruvbox-dark"

  # search
  enableSearch = true

  stickyNav = true
  showSummaryCoverInPost = true
  showTableOfContents = true
  reorderNavItems = ["about", "search", "rss", "posts", "categories", "tags"]
  collapseNavItems = ["posts", "categories", "tags"]

[params.advanced]
  customCSS = ["css/custom.css"]

[params.experimental]
  jsDate = true

[params.counter.busuanzi] 
  enable = true